### ISSUE TITLE
[Suggestion] Wiki page?

### ISSUE THREAD

**Issue by qawery-just-sad** [surftimer/Surftimer-olokos#120]
**Is your feature request related to a problem? Please describe.**
I know we have that [discord server](https://discord.gg/xDtMpPm) where we (try to) help people, the problem is when they make one small mistake, it all goes south.

**Describe the solution you'd like**
Let's create wiki page on github. A good representation of a wiki page would be this one (https://github.com/Impact123/CallAdmin/wiki)

**Describe alternatives you've considered**
Sudoku or Rubik's cube, alternatively better installation guide.

**Additional context**
> "...the instructions are very confusing for people like i ... that have no experience with this at all..." - Kyli3_Boi

> "This is a mess..." - Guy from high tech company (friend of mine)

**Comment by Bara** [comment]
That's already on our todo list, using the github wiki with gitbook as a clean docs site. We also planned a few more changes to make it more easier to install.

**Comment by Bara** [comment]
Still blank, but WIP.
https://docs.surftimer.io/sourcemod/
