### ISSUE TITLE
Does the plugin auto adds zones and tiers or do i have to include all zones manually[Suggestion]

### ISSUE THREAD

**Issue by Spry-T** [surftimer/Surftimer-olokos#121]
Does it have !insertmapzones and !insertmaptiers or should i include all zones manually

**Comment by Kyli3Boi** [comment]
Run csgo/scripts/mysql-files/ck_maptier.sql & csgo/scripts/mysql-files/ck_zones.sql in your surftimer database (if you want to use the premade zones & maptiers)
