### ISSUE TITLE
[BUG] Timer SR not displaying correct time

### ISSUE THREAD

**Issue by Kyli3Boi** [surftimer/Surftimer-olokos#122]
**Describe the bug**

The time in SR (CP) which is supposed to display a comparison between your time and the server record time is not functioning correctly and is displaying that you are ahead of the record when in actual fact you are not.

**Expected behavior**

The time in SR should display a comparison between your current time and the server record time for that map

**Screenshots**

![image](https://user-images.githubusercontent.com/64275139/81820948-90976b00-9531-11ea-990d-d0409b1065ce.png)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

01 "Admin File Reader" (1.10.0.6488) by AlliedModders LLC
  02 "SQL Admins (Threaded)" (1.10.0.6488) by AlliedModders LLC
  03 "Admin Help" (1.10.0.6488) by AlliedModders LLC
  04 "Admin Menu" (1.10.0.6488) by AlliedModders LLC
  05 "AFK Manager" (4.3.0) by Rothgar
  06 "Anti-Flood" (1.10.0.6488) by AlliedModders LLC
  07 "Basic Ban Commands" (1.10.0.6488) by AlliedModders LLC
  08 "Basic Chat" (1.10.0.6488) by AlliedModders LLC
  09 "Basic Comm Control" (1.10.0.6488) by AlliedModders LLC
  10 "Basic Commands" (1.10.0.6488) by AlliedModders LLC
  11 "Basic Info Triggers" (1.10.0.6488) by AlliedModders LLC
  12 "Basic Votes" (1.10.0.6488) by AlliedModders LLC
  13 "Client Preferences" (1.10.0.6488) by AlliedModders LLC
  14 "Command hider" (1.0) by Author zipcore Compiled by Playa
  15 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  16 "Discord API" (0.1.103) by Deathknife
  17 "Fun Commands" (1.10.0.6488) by AlliedModders LLC
  18 "Fun Votes" (1.10.0.6488) by AlliedModders LLC
  19 "SurfTimer MapChooser" (1.10.0.6336) by AlliedModders LLC & Ace
  20 "Momentum surf fix '2" (1.1.2) by GAMMA CASE
  21 "Nextmap" (1.10.0.6488) by AlliedModders LLC
  22 "SurfTimer Nominations" (1.10.0.6336) by AlliedModders LLC & Ace
  23 "Paint!" (1.1) by SlidyBat
  24 "Player Commands" (1.10.0.6488) by AlliedModders LLC
  25 "RandomCycle" (1.10.0.6488) by AlliedModders LLC
  26 "Reserved Slots" (1.10.0.6488) by AlliedModders LLC
  27 "SurfTimer Rock The Vote" (1.10.0.6336) by AlliedModders LLC & Ace
  28 "ServerAdvertisements3" (3.1.4) by ESK0
  29 "Sound Commands" (1.10.0.6488) by AlliedModders LLC
  30 "SQL Admin Manager" (1.10.0.6488) by AlliedModders LLC
  31 "SurfTimer" (285.5) by Ace & olokos
  32 "SteamWorks Additive Glider" (1.0) by Kyle Sanderson
  33 "Trails Chroma" (2.4) by Nickelony

**Additional context**

I think this could be the reason why my bots are also not functioning as they should. Playing records from players that are other ranks except for the server record run

**Comment by sneak-it** [comment]
The CP comparisons are comparing against the best recorded CP's. Was your ck_checkpoints table messed with or wiped at some point perhaps?

**Comment by Kyli3Boi** [comment]
I wouldnt say that i havent touched anything, iv been struggling with so many issues that i have been playing with everything so its very possible that this could be a error on my side.

If you could just give some insight on how to fix it that would be great. If i need to delete times etc please let me know which ones as id rather get this done sooner than later

**Comment by LubricantJam** [comment]
> I wouldnt say that i havent touched anything, iv been struggling with so many issues that i have been playing with everything so its very possible that this could be a error on my side.
> 
> If you could just give some insight on how to fix it that would be great. If i need to delete times etc please let me know which ones as id rather get this done sooner than later 

Unsure on how you think we can give you a diagnosis without actually helping with what you've got going on.

**Comment by Kyli3Boi** [comment]
Thanks LubricantJam ill give that a go.

If i give you guys screenshots of my DB would you be able to tell if it looks fine or if something is out of place?
