### ISSUE TITLE
[BUG]Failed to grow array

### ISSUE THREAD

**Issue by Spry-T** [surftimer/Surftimer-olokos#124]
Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] PushArrayArray
[SM]   [1] Line 926, surftimer/replay.sp::RecordReplay
[SM]   [2] Line 1082, surftimer/hooks.sp::OnPlayerRunCmd
[SM] Exception reported: Failed to grow array

**Comment by sneak-it** [comment]
Can't help you if you delete the bug report format.

**Comment by Bara** [comment]
and you don't provided the whole log of this error.
