### ISSUE TITLE
[BUG] exception when !rm was used 

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/Surftimer-olokos#134]
**Describe the bug**
I used !rm and noticed this in the console
[SM] Exception reported: Handle 3c10289 is invalid (error 1)
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 1843, SurfTimer.sp::OnMapEnd

**Expected behavior**

**Screenshots**

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
im on 285.95

**Additional context**

**Comment by Bara** [comment]
We should replace `CloseHandle` with `delete`.

**Comment by FR33K1LL** [comment]
@Bara is this exception related?
[SM] Exception reported: Handle 3c10289 is invalid (error 1)
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 1843, SurfTimer.sp::OnMapEnd

**Comment by Bara** [comment]
Should be fixed with #147
