### ISSUE TITLE
[BUG] "%" idk 

### ISSUE THREAD

**Issue by qawery-just-sad** [surftimer/Surftimer-olokos#137]
**Describe the bug**
When typing in chat "%spec" or any other command "%back" this happenes
![image](https://user-images.githubusercontent.com/53490397/82150679-33652780-9859-11ea-9f17-20365f8c8916.png)

**Expected behavior**
Actually idk foward the msg with % and whatever?

**Plugin List**
timer version 285 and 285.95 on olokos test server

**Additional context**
On 285 while spectating:
Just Sad: %spec
L 05/17/2020 - 16:03:06: [SM] Exception reported: String formatted incorrectly - parameter 3 (total 2)
L 05/17/2020 - 16:03:06: [SM] Blaming: SurfTimer.smx
L 05/17/2020 - 16:03:06: [SM] Call stack trace:
L 05/17/2020 - 16:03:06: [SM]   [0] PrintToChat
L 05/17/2020 - 16:03:06: [SM]   [1] Line 1039, C:\Users\oloko\Documents\GitHub\Surftimer-BUILD\include\colorvariables.inc::SendPlayerMessage
L 05/17/2020 - 16:03:06: [SM]   [2] Line 113, C:\Users\oloko\Documents\GitHub\Surftimer-BUILD\include\colorvariables.inc::CPrintToChatAll
L 05/17/2020 - 16:03:06: [SM]   [3] Line 2559, surftimer/misc.sp::PrintSpecMessageAll
L 05/17/2020 - 16:03:06: [SM]   [4] Line 456, surftimer/hooks.sp::Say_Hook

On 285 while alive:
Just Sad: %spec
L 05/17/2020 - 16:17:05: [SM] Exception reported: String formatted incorrectly - parameter 3 (total 2)
L 05/17/2020 - 16:17:05: [SM] Blaming: SurfTimer.smx
L 05/17/2020 - 16:17:05: [SM] Call stack trace:
L 05/17/2020 - 16:17:05: [SM]   [0] PrintToChat
L 05/17/2020 - 16:17:05: [SM]   [1] Line 1039, C:\Users\oloko\Documents\GitHub\Surftimer-BUILD\include\colorvariables.inc::SendPlayerMessage
L 05/17/2020 - 16:17:05: [SM]   [2] Line 113, C:\Users\oloko\Documents\GitHub\Surftimer-BUILD\include\colorvariables.inc::CPrintToChatAll
L 05/17/2020 - 16:17:05: [SM]   [3] Line 473, surftimer/hooks.sp::Say_Hook
Just Sad: %spec

**Comment by Bara** [comment]
`[...]colorvariables.inc[...]` sounds like a older version. Upgrade to the latest version, if this issue is still happening, reopen this issue or create new one.
