### ISSUE TITLE
[BUG] SQL_UpdateStyleRecordCallback error

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/Surftimer-olokos#138]
**Describe the bug**
This appears in my logs,
[SurfTimer.smx] [SurfTimer] SQL Error (SQL_UpdateStyleRecordCallback): Field 'velStartXY' doesn't have a default value

**Expected behavior**

**Screenshots**
These screenshots could be what happens because of this error, im not 100%.
![rank 0](https://user-images.githubusercontent.com/63484108/82263690-4ee33780-9918-11ea-923f-1d8acd71731e.PNG)
![rank 99999](https://user-images.githubusercontent.com/63484108/82263742-67535200-9918-11ea-8b4b-85bda40b9bdf.PNG)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
285.95

**Additional context**
Sometimes when someone beats a map in a style, they will get a rank of 0/14 , and i *think* this error pops when that tries to happen. Im not a 100%

**Comment by Bara** [comment]
velStart and velEnd has a default value of 0. I'll take a look when I'm back
