### ISSUE TITLE
[BUG] freestyle does not show in !top menu

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/Surftimer-olokos#143]
**Describe the bug**
Freestyle is missing from the !top menu

**Expected behavior**

**Screenshots**

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.95

**Additional context**
ive made a commit to fix this, and created this issue so i could reference it in the pr

**Comment by Bara** [comment]
https://github.com/surftimer/Surftimer-olokos/pull/144
