### ISSUE TITLE
[BUG] SQL Error SQL_UpdateWrcpRecordCallback 

### ISSUE THREAD

**Issue by evil-saint** [surftimer/Surftimer-olokos#160]
SQL Error SQL_UpdateWrcpRecordCallback , Field 'velStartXY' does not have default value

![image](https://user-images.githubusercontent.com/66045697/83088762-3f02ea80-a0b2-11ea-9e50-8ce8ee1ce3f9.png)

Surftimer version - 285

**Comment by Bara** [comment]
Duplicate of #138
