### ISSUE TITLE
[Question] Remote Replay bot files

### ISSUE THREAD

**Issue by damndudeomg** [surftimer/Surftimer-olokos#163]
ok

**Comment by qawery-just-sad** [comment]
erm symlink? or setup a cornjob to copy files to other servers? idk just throwing ideas

**Comment by damndudeomg** [comment]
> erm symlink? or setup a cornjob to copy files to other servers? idk just throwing ideas

nah, cronjob can't help. Secondary servers must be able to read everytime files from Master server's replays directory, and also must be able to write new file if record is beated.

**Comment by dPexxIAM** [comment]
Use symbolic links, as @qawery-just-sad suggested.

**Comment by MestroGroup** [comment]
Good morning,
You should be able to do this using Symlinks if you're using a Linux based system.

Kind Regards

**Comment by damndudeomg** [comment]
> Use symbolic links, as @qawery-just-sad suggested.

What if these servers are in different dedicated servers?

**Comment by MestroGroup** [comment]
> > Use symbolic links, as @qawery-just-sad suggested.
> 
> What if these servers are in different dedicated servers?

You can mount a directory from a remote server.

Regards

**Comment by dPexxIAM** [comment]
> > > Use symbolic links, as @qawery-just-sad suggested.
> > 
> > 
> > What if these servers are in different dedicated servers?
> 
> You can mount a directory from a remote server.
> 
> Regards

This will cause your server to lag constantly, would not advise doing so.



> > Use symbolic links, as @qawery-just-sad suggested.
> 
> What if these servers are in different dedicated servers?

From what I've found, it's not really possible. 

I have not been able to find a solid solution, sadly.

**Comment by damndudeomg** [comment]
Is there a really way to 'ln -s' sftp link to local path folder?

**Comment by damndudeomg** [comment]
> > > Use symbolic links, as @qawery-just-sad suggested.
> > 
> > 
> > What if these servers are in different dedicated servers?
> 
> You can mount a directory from a remote server.
> 
> Regards

Can you please give an idea how?

**Comment by dPexxIAM** [comment]
> > > > Use symbolic links, as @qawery-just-sad suggested.
> > > 
> > > 
> > > What if these servers are in different dedicated servers?
> > 
> > 
> > You can mount a directory from a remote server.
> > Regards
> 
> Can you please give an idea how?

Use google and stop spamming this thread. Besides the fact that github issues aren't the place to be asking these type of questions. You've been given multiple solutions. I'm closing this issue.

**Comment by damndudeomg** [comment]
Damn, I am sorry because you're mad. Maybe you have some kind a private problems.

Then you're answer is "I don't know how and I will not give even a chance to the other developers try to help you, I will just close this issue."

Thank you so much. <3

**Comment by dPexxIAM** [comment]
I find it hilarious that your train of thought lead you to that conclusion. 

I'll re-open the thread for now.

**Comment by qawery-just-sad** [comment]
looks like someone can't use google to solve ez problems (looking at @damndudeomg )
