### ISSUE TITLE
[Suggestion] Style Shortcuts

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#164]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
If possible add **shortcut commands to styles** and not only normal. (can just be ranked styles)
```
sm_n = normal
sm_hsw = half side-ways
sm_bw = backwards
sm_sw = side-ways
etc..

```

**Comment by qawery-just-sad** [comment]
https://github.com/surftimer/Surftimer-olokos/blob/d9aaca640205918e9bbc9881150f43d4e03d2ec3/addons/sourcemod/scripting/surftimer/commands.sp#L84

**Comment by stunslave** [comment]
> https://github.com/surftimer/Surftimer-olokos/blob/d9aaca640205918e9bbc9881150f43d4e03d2ec3/addons/sourcemod/scripting/surftimer/commands.sp#L84

If possible also adding **shortcut commands to styles** and _not only normal._

**Comment by qawery-just-sad** [comment]
this has been solved with #165

**Comment by stunslave** [comment]
Maybe add to this timer also? :>

**Comment by tslashd** [comment]
> Maybe add to [this timer](https://github.com/surftimer/Surftimer-Official) also? Thanks.. :>

https://github.com/surftimer/Surftimer-Official/blob/75cee577ae0bc98af9e358acbc80103733ff8057/addons/sourcemod/scripting/surftimer/commands.sp#L84
