### ISSUE TITLE
Can't import SQL ck_maptier.sql

### ISSUE THREAD

**Issue by RadiateTC** [surftimer/Surftimer-olokos#173]
Hey, i've just setted up my server with this plugin since yesterday, everything works fine besides the SQL import ck_maptier.sql, i'm getting the following error #1136 - Column count doesn't match value count at row 1

anyone, out there managed to get that working?

**Comment by qawery-just-sad** [comment]
yea the ck_maptier is missing ranked column just need to add that and u'll be fine
