### ISSUE TITLE
[Suggestion] Auto-Purge database after x days

### ISSUE THREAD

**Issue by breakthegreat** [surftimer/Surftimer-olokos#175]
**Is your feature request related to a problem? Please describe.**
This could fix loading issue, or simply be easier for surf server owner to set up monthly leaderboard

**Describe the solution you'd like**
The plugins would add a cvar to auto-urge/delete the player rank and times after a certains amount of days pr days of inactivity.

**Additional context**
I couldn't find anything in the main plugins supporting this idea, I do apologize if it's something that has been already implemented or suggested I'm just trying to give some ideas here and there. Thanks for the great job you are doing guys keep going!

**Comment by dPexxIAM** [comment]
Deleting inactive player-data is a no go. What if the player who was inactive held X amount of records for instance? You can probably see the issues this could cause.

**Comment by sneak-it** [comment]
Wiping data is not a solution, and would be more damaging than it helps. The real solution here is to optimize database structure, storage, and queries.

If you wish to purge your own player's data, you may do so.

**Comment by olokos** [comment]
If you really want to do it monthly, then you could set-up a script that deletes the data out of the tables, whatever you want to delete and then run a cronjob each month.

As for implementing it within the plugin itself, I think sneak and dpexx have already made it clear. 😄
