### ISSUE TITLE
[BUG] Script Execution

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#183]
**Describe the bug**
When a player connects to the server, within 5 seconds the server disconnects and reloads the map on a continues loop.

This bug only happens on certain maps, I don't know what causes it other than the replay bots are part of the problem and disabling the bots fixes it. Tested on map surf_concretejungle

https://pastebin.com/FgwAD7c4

**Screenshots**
![image](https://user-images.githubusercontent.com/47533535/83978121-8afd2d00-a905-11ea-853a-8edc9b59ec73.png)

**Timer Version**
Version 1.0.1
Also happens on [⎝⧹⎛olokos⎞⧸⎠](https://discordapp.com/channels/366959507764674560/379572504542445568/719264766152933466)  Compiled version. (This bug and the 99999/ bug)

**Comment by olokos** [comment]
![Image Notepad++](https://image.prntscr.com/image/zDTwkDNHTYaask77o-hSIQ.png)
I don't know man, those are logs from my server, searched for the issue you're reporting, but I could not reproduce this bug.

I searched through logs from 06/07/2020 to 06/10/2020 and no occurence of Script execution timed out on my server, maybe you're running out of ram/slow cpu/hdd/internet/db?

**Comment by sneak-it** [comment]
Can you please try the latest version and let us know if you have the same issue @stunslave ? I tried looking into your issue @ the version you specified, however the line that is being blamed doesn't line up with your error.

**Comment by olokos** [comment]
No response for such a long time, so I'm closing this.
