### ISSUE TITLE
[BUG] SQL Query infinite loop

### ISSUE THREAD

**Issue by olokos** [surftimer/Surftimer-olokos#184]
**Describe the bug**
MySQL gets spammed with this query, iterating over ck_vipadmins endlessly
`2020-06-08T15:51:29.976553Z	21302 Query	SELECT vip, admin, zoner FROM ck_vipadmins WHERE steamid = 'STEAM_1:1:xxxx'

**Expected behavior**
MySQL queries should not be executed unless neccesary.

**Timer Version**
1.0.1

**Additional context**
46193 queries within 10 minutes are fired and saved to /var/log/mysql/mysql.log

**Comment by olokos** [comment]
Do you have an idea @Bara ? 
It might be related to the recent changes.

**Comment by olokos** [comment]
It's defined here
https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L9219

**Comment by olokos** [comment]
And called here
https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/vip.sp#L163

https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/vip.sp#L229

https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/misc.sp#L103

https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L9268

and lastly, here:
https://github.com/surftimer/Surftimer-olokos/blob/dev/addons/sourcemod/scripting/surftimer/sql.sp#L9275

I need some rest now, very busy day.

**Comment by StAwN74** [comment]
Hi, I'm working on ckSurf too and I read this infinite loop and could not help writing here :)
Hope it's ok. I just discovered main memory leak comes from a loop at PlayReplay, when a second bonus bot is called at the end of its run. Only bonus bot, it's weird. It adds 2 array handles (Think it's Array_Copy) and I don't know how to clear or close these. I'm really sry if I should not write here but I was thinking we could help each other. GL

**Comment by Bara** [comment]
@StAwN74 Array_Copy shouldn't be matter here. It just copy int/float arrays, which don't need to be closed.

More interesting is the Handle [hAdditionalTeleport](https://github.com/surftimer/Surftimer-olokos/blob/df381eeef006b1059bfd9331befd62fb0f34ea4b/addons/sourcemod/scripting/surftimer/replay.sp#L1102) that is being created, but never closed (multiple times in replay.sp?). But I currently don't have the motivation to debug/test/change this.

**Comment by StAwN74** [comment]
Yes true, this handle is problem too.  But now you guys and I have closed it in LoadRecordFromFile().
And I say this because the dumps show that Array Handles are growing, not the other handles.
So either an Array problem, or we need to close this handle elsewhere too.

**Comment by olokos** [comment]
Apparently this function was infinitely recursing, causing loads of stress on the database, thus causing all of those performance issues as reported earlier.

With above commit the mysql query spam is gone and mysql.log doesn't produce 46k queries anymore within 10 minutes 🙂
