### ISSUE TITLE
[BUG] !stage isn't working

### ISSUE THREAD

**Issue by olokos** [surftimer/Surftimer-olokos#185]
**Describe the bug**
Array index out of bounds 

**Expected behavior**
Should teleport to stage stopping the timer

**Timer Version**
1.0.1

**Additional context**
```
L 06/09/2020 - 01:53:59: [SM] Exception reported: Array index out-of-bounds (index -1, limit 128)
L 06/09/2020 - 01:53:59: [SM] Blaming: SurfTimer.smx
L 06/09/2020 - 01:54:00: [SM] Call stack trace:
L 06/09/2020 - 01:54:00: [SM]   [1] Line 186, surftimer/misc.sp::teleportClient
L 06/09/2020 - 01:54:00: [SM]   [2] Line 1047, surftimer/commands.sp::Command_ToStage
```

Happened on surf_beginner after `!s 3`

**Comment by olokos** [comment]
This seems to happen when !stage is used on linear maps, so there's no stage to teleport to.

**Comment by Kyli3Boi** [comment]
Can confirm this is now fixed. Thank you
