### ISSUE TITLE
[BUG] Discord time error

### ISSUE THREAD

**Issue by Kyli3Boi** [surftimer/Surftimer-olokos#197]
**Describe the bug**
When a player completes a map for the 1st time whilst breaking the SR, the discord notification will display their time as the time gained over the previous record 

E.G (2nd notification in image)
00:53:25 (+00:53:25) 

**Expected behavior**
The player that completes a map for the 1st time whilst breaking the SR, time should be displayed as a - of the current SR

E.G
00:53:25 (-00:01:35)

**Screenshots**
The 1st notification is the SR being set (there was no record before this)
The 2nd notification is the SR (in 1st notification) being beaten

![Capture](https://user-images.githubusercontent.com/64275139/86068890-b7294b00-ba78-11ea-95f7-0db7ae71ce11.PNG)

**Plugin List**
N/A

**Timer Version**
286

**Additional context**
N/A

**Comment by qawery-just-sad** [comment]
If you use my fork put the issue there not in here

**Comment by Kyli3Boi** [comment]
Using olokos

**Comment by qawery-just-sad** [comment]
100% sure that happens on my fork and 90% sure olokos never put 286 in any realase of dev branch here

**Comment by Kyli3Boi** [comment]
![image](https://user-images.githubusercontent.com/64275139/86107939-cdf48f80-bac2-11ea-9579-90a4eb9f11f7.png)

**Comment by olokos** [comment]
Well, current version is 1.0.2 and 286 was considered as unreleased dev version
285 is the latest "master-stable" version

Currently you're not testing neither latest dev nor latest master, I suggest you to go with latest dev code as there were changes past 286 to discord annoucements aswell.

**Comment by Kyli3Boi** [comment]
Once #181 is fixed ill move to 1.0.2. Id rather have broken discord than broken server

**Comment by Kyli3Boi** [comment]
Fixed with #198
