### ISSUE TITLE
[BUG] Tier Limit

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#201]
**Describe the bug**
Setting the maps tier to 8 cause the db mapcycle to bug out and sends the below error msg to console.
Current limit is 7 and needs to be changed to 8.

**Additional context**
07/07/2020 - 12:08:42: [SM] Exception reported: Array index out-of-bounds (index 8, limit 7)
L 07/07/2020 - 12:08:42: [SM] Blaming: surftimer.smx
L 07/07/2020 - 12:08:42: [SM] Call stack trace:
L 07/07/2020 - 12:08:42: [SM]   [1] Line 9922, surftimer/sql.sp::SQL_SelectMapCycleCallback

**Timer Version**
Prerelease 1.0.2 - development version

**Comment by KristianP26** [comment]
Same problem.

**Comment by olokos** [comment]
I think it's fixed with #203 
If this is still not resolved with this, please do @ me here and I'll reopen.
