### ISSUE TITLE
[Suggestion] One Jump Limit

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#210]
**Describe the solution you'd like**
I would like **ck_one_jump_limit** to be added to sm_mapsettings, so that one jump limit can be **enabled per map** and not on all maps. 

**Additional context**
One jump is great to use on maps with a start booster to stop crouch boosting, but it is not great to have it enabled on a lot of other maps and can cause a lot of problems with certain styles and practice mode.

As it is currently I prefer to have it disabled, but would like to enable it on certain maps if possible.

**Comment by sneak-it** [comment]
You can set different any cvar you want on a per-map basis with this plugin: https://forums.alliedmods.net/showthread.php?p=607079

**Comment by stunslave** [comment]
No thanks I have used custom map configs before for minigames/hns/combat surf etc. That is way to much effort. (Ill rather leave it disabled) I don't have 3 months (Slight exaggeration) to setup the per map configs.

**Comment by sneak-it** [comment]
It's quite literally one line in a cfg file, you would have to individually specify the one jump limit on a per-map basis regardless of whether it was in that format or not.

**Comment by Kyli3Boi** [comment]
If you change it in the db will it not work?

**Comment by qawery-just-sad** [comment]
> If you change it in the db will it not work?

Exactly as @Kyli3Boi said, in map settings on second page there is option to disable one jump limit for all zones on current map,
you can do that also through db.
idk what's your problem

**Comment by stunslave** [comment]
O awesome I didn't notice there was a second page in map-settings! lol
Thanks - I'll close this Post.
