### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DroneN1456** [surftimer/Surftimer-olokos#213]
**Describe the bug**
A actually dont know if it is a bug or just me being dumb, but is related to the databases, i already setuped the "surftimer" in databases.cfg but it simple doesnt work 
[SM] Exception reported: [SurfTimer] Unable to connect to database ([2003]: Can't connect to MySQL server on 'localhost' (10061))

**Expected behavior**
The plugin working

**Screenshots**

**Plugin List**

**Additional context**
i already searched a lot of this error, tried everthing that i know, but nothing worked, tried using "2003" as port, "10061" as port, using the localhost ip instead of "localhost", i tried everthing that i have knowledge, please i really need help

**Comment by Kyli3Boi** [comment]
Hey there. Please can you join the discord and ask for assistance as this is not a bug.

**Comment by sneak-it** [comment]
**Installation and Requirements**
- A MySQL Database (MySQL 5.7, MySQL 8+, MariaDB supported)
