### ISSUE TITLE
[BUG] Center Speed hud is disabled by default

### ISSUE THREAD

**Issue by qawery-just-sad** [surftimer/Surftimer-olokos#237]
**Describe the bug**
Center Speed hud is disabled by default.

**Expected behavior**
Center Speed hud should be enabled by default

**Screenshots**

**Plugin List**
dev 1.0.2

**Additional context**
When database is created the default for centrespeed is 0 should be 1.
https://github.com/surftimer/Surftimer-olokos/blob/1949a901c414adf5dad7b4f8ac9b89c36b7fa265/addons/sourcemod/scripting/surftimer/db/queries.sp#L42

**Comment by Kyli3Boi** [comment]
Uhm why would we want this enabled by default?? Not many people even use this.

On my servers out of the 3675 player entries only 14 actually have this on

**Comment by qawery-just-sad** [comment]
well 258/267 have it enabled on my, and it was always enabled, and https://discordapp.com/channels/366959507764674560/379572504542445568/747901778539970580
i think there were like 20 convos about that on the discord

**Comment by Kyli3Boi** [comment]
In that Discord message he is talking about the HUD "usual center hint, containing the time and stuff" not the centrespeed which is the speed displayed in the middle of the screen.

**Comment by qawery-just-sad** [comment]
oopsie wrong one?

**Comment by qawery-just-sad** [comment]
reverse changes sorry @Bara

**Comment by Kyli3Boi** [comment]
^^

**Comment by qawery-just-sad** [comment]
that's what happenes when i'm drunk/sad/evening
