### ISSUE TITLE
[BUG] Bot stuck and spamming console

### ISSUE THREAD

**Issue by 13ace37** [surftimer/Surftimer-olokos#54]
**Describe the bug**
But stucks at the end of the ramp for no reason (might be some sort of rampglitch) and stops moving completely. Console spamming with errors:
![image](https://user-images.githubusercontent.com/29045525/80149556-271ddf80-85b7-11ea-9d54-14baab885d31.png)

**Plugin List**
Nothing special clean server w/ latest dev.

**Comment by breakthegreat** [comment]
same here

**Comment by breakthegreat** [comment]
![image](https://user-images.githubusercontent.com/64219376/80343322-ab7c9680-8833-11ea-8bdf-e015c13e02f9.png)

**Comment by olokos** [comment]
can you reproduce this with 1.0.1 @13ace37 ?
