### ISSUE TITLE
[BUG]Timer HUD not show on center of the screen

### ISSUE THREAD

**Issue by xFlume** [surftimer/Surftimer-olokos#55]
the plugin is work all good but the timer hud not show up how can i fix it ?

**Comment by sashajov** [comment]
Can you send error logs?

**Comment by 13ace37** [comment]
If you updated from the old surftimer make sure to run all the update SQL files

**Comment by xFlume** [comment]
i didnt upgrade i opened new server
i not have errors all works good but the HUD not showup

**Comment by olokos** [comment]
Check your databases.cfg

**Comment by sashajov** [comment]
@xFlume did you follow these instructions: https://github.com/olokos/Surftimer-olokos/blob/dev/README.md#installation-and-requirements

**Comment by xFlume** [comment]
yea and my database.cfg is fine i added surftimer database

**Comment by olokos** [comment]
Provide logs from the server.

**Comment by xFlume** [comment]
L 04/24/2020 - 12:26:17: Log file started (file "logs\L000_000_000_000_0_202004241226_000.log") (game "E:\TCAFiles\Users\csgo-owner\65\csgo") (version "7803")
L 04/24/2020 - 12:26:17: server_cvar: "sv_password" "***PROTECTED***"
L 04/24/2020 - 12:26:19: server_cvar: "sv_alltalk" "1"
L 04/24/2020 - 12:26:19: server_cvar: "sv_friction" "4"
L 04/24/2020 - 12:26:19: server_cvar: "mp_maxrounds" "30"
L 04/24/2020 - 12:26:19: server_cvar: "mp_timelimit" "0"
L 04/24/2020 - 12:26:19: server_cvar: "mp_roundtime" "2"
L 04/24/2020 - 12:26:19: server_cvar: "mp_freezetime" "5"
L 04/24/2020 - 12:26:19: server_cvar: "mp_friendlyfire" "1"
L 04/24/2020 - 12:26:19: server_cvar: "mp_c4timer" "45"
L 04/24/2020 - 12:26:19: server_cvar: "mp_roundtime" "3"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_terrorist_win_bomb" "2200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_elimination_bomb_map" "2200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_win_by_defusing_bomb" "2200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_win_by_hostage_rescue" "2200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_loser_bonus" "2000"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_rescued_hostage" "100"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_planted_bomb_but_defused" "200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_team_hostage_interaction" "50"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_killed_teammate" "-3300"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_killed_enemy_default" "200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_killed_enemy_factor" "0.5"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_bomb_planted" "200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_bomb_defused" "200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_rescued_hostage" "200"
L 04/24/2020 - 12:26:19: server_cvar: "cash_player_interact_with_hostage" "0"
L 04/24/2020 - 12:26:19: [META] Loaded 1 plugin.
L 04/24/2020 - 12:26:19: Log file closed

**Comment by nopeh** [comment]
I am also experiencing this issue, however the hud timer shows up in when spectating other players.   I'll work on getting the logs tomorrow.

**Comment by LubricantJam** [comment]
Only doesn't load for me when the player hasn't initialised and got their profile yet. That's it.

**Comment by xFlume** [comment]
> Only doesn't load for me when the player hasn't initialised and got their profile yet. That's it.

i try this too but its not loaded when i finish 1 map to load the profile

**Comment by olokos** [comment]
> > Only doesn't load for me when the player hasn't initialised and got their profile yet. That's it.
> 
> i try this too but its not loaded when i finish 1 map to load the profile

Try building current dev branch 😉

**Comment by xFlume** [comment]
> > > Only doesn't load for me when the player hasn't initialised and got their profile yet. That's it.
> > 
> > 
> > i try this too but its not loaded when i finish 1 map to load the profile
> 
> Try building current dev branch 😉

where can i download this build ?

**Comment by xFlume** [comment]
still waiting for answer...

**Comment by dPexxIAM** [comment]
could the hud be disabled by default in ck_playeroptions2 by chance?

**Comment by olokos** [comment]
@xFlume 
Everything you need to compile the plugin yourself is in the Readme.md
Short version:
Download sourcemod,dependencies and double click compile.exe
The details are in Readme.md or once you scroll down on the repository.

You can also join my server, which is running latest version 1.0.1, which is currently the latest code as of writing this.

``connect kiepownica.pl``

**Comment by olokos** [comment]
No reply for months so I'm closing this issue.
