### ISSUE TITLE
[Suggestion] Move SQL migrations to user-initiated command

### ISSUE THREAD

**Issue by sneak-it** [surftimer/Surftimer-olokos#80]
**Is your feature request related to a problem? Please describe.**
It is apparent that there are many database modifications happening that add new features, fix database issues, and will be more in the future as we optimize database storage. With every migration, several unnecessary queries are executed every map start which slow down the timer loading necessary information.

**Describe the solution you'd like**
Given that the timer will fail to load if certain tables/columns are missing, I suggest we use a dedicated module (ex. surftimer-migrations) to initiate all database migrations. These migrations can be run by the server owner when they upgrade versions, and we can indicate in release notes if migrations need to happen on a per-version basis.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Any thoughts?

**Comment by LubricantJam** [comment]
Sounds logical to me, it's just a bit silly having all these random SQL files lying all around the place.

**Comment by olokos** [comment]
Great idea!
We could be shipping Surftimer-Migrations.smx along with Surftimer.smx and make it a requirement for first installation or between releases.
