### ISSUE TITLE
[BUG] He doesn't put me back on the team if I joined the spectators

### ISSUE THREAD

**Issue by SergiuSA123** [surftimer/Surftimer-olokos#83]
**Describe the bug**

**Expected behavior**

If I try to get back to the team after I went to the spectators, it doesn't respawn me, and I have to reconnect to the server, but if I change the folder again in the same one, it recovers, I'm not on all the maps, the problem appears randomly
**Screenshots**
i tink we don't need
**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.
Only SURFTIMER, and voicerooms
**Additional context**
pls help

**Comment by sneak-it** [comment]
Anything in your Sourcemod error logs?

**Comment by samatazz** [comment]
I dont think this is a timer issue. Is mp_respawn_on_death_ct and _t set to 1? I had this issue briefly as they wernt set

**Comment by stunslave** [comment]
This normally happens if the map is not restarted after zoning and adding the tier info.

**Comment by Xedoo** [comment]
> 
> 
> Anything in your Sourcemod error logs?

No errors in logs, already checked everything.



> 
> 
> I dont think this is a timer issue. Is mp_respawn_on_death_ct and _t set to 1? I had this issue briefly as they wernt set

Where can i find this ?

**Comment by sneak-it** [comment]
> Where can i find this ?

Check your server cvars

**Comment by nopeh** [comment]
reloading the map after zoning fixes this for me.

**Comment by olokos** [comment]
> I dont think this is a timer issue. Is mp_respawn_on_death_ct and _t set to 1? I had this issue briefly as they wernt set

I bet this is it and I cannot reproduce it with those 2 cvars set.
