### ISSUE TITLE
[Enhancement] Improve bots movetype by changing it to noclip

### ISSUE THREAD

**Issue by olokos** [surftimer/Surftimer-olokos#98]
**Describe the bug**
Bots might not be perfectly smooth, as reported by some people

**Expected behavior**
Bots should be as smooth as an actual player

**Additional context**
@ghost has submitted a PR that changed the movetype to noclip
#20 
We need to reevalute smoothness of bots movements, especially with the upcoming 286 release.
I haven't noticed any issues myself, but it's worth trying out if bot movetype noclip is an improvement or not.

**Comment by deadw1nter** [comment]
I think the only way to make bots smooth is rewriting the whole replay. Because the code is kind of messy and overcomplicated.

**Comment by qawery-just-sad** [comment]
tbh this whole plugin needs a rewrite

**Comment by olokos** [comment]
I suppose setting noclip didn't fix the issue and a comment with this idea is already in the code, so closing this.
